version: "3.3"
services:
  app:
    image: cgc-cloud
    network_mode: host
    environment:
      - PORT=5000
      - FIRESTORE_HOST=localhost:8080
      - FIRESTORE_PROJECT_ID=test-project
      - FIRESTORE_SSL=false
    depends_on:
      - emulators

  emulators:
    image: firebase
    build:
      context: .
      dockerfile: firebase.Dockerfile
    network_mode: host
    command: firebase emulators:start --only firestore --project test-project
