name: ci

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build

  lint:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: |
          npm install
          npm run build
