name: ci

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build

  lint:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: |
          npm install
          npm run lint

  unit-tests:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: |
          npm install
          npm run test

  system-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing dependencies
        run: npm install
      
      - name: Building app image
        run: npm run image
      
      - name: Running system tests
        run: npm run system-tests
