name: cd

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Build the image
        run: |
          echo ${{ secrets.GH_PAT }} | docker login ghcr.io --username ${{ secrets.GH_USER }} --password-stdin
          docker build --no-cache -t ${{ github.repository }} .
      - name: Publish the image
        run: |
          docker tag ${{ github.repository }} ghcr.io/${{ github.repository }}/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}/${{ github.repository }}:latest
