name: publish-docker

on:
  push:
    branches: main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo ${{ secrets.GH_PAT }} | docker login ghcr.io --username ${{ secrets.GH_USER }} --password-stdin
          docker build --no-cache -t ghcr.io/${{ github.repository }}:latest .
      - name: Publish
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
